<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupportRepository extends EntityRepository
{
    public function getUsersWithNewMessages(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT IDENTITY(s.user) as id, u.username as username, COUNT(s.user) as new_msgs FROM AppBundle:Support s INNER JOIN UserBundle:User u WITH s.user = u.id WHERE s.isRead = 0 AND s.isAnswer = 0 GROUP BY s.user"
            )
            ->getResult();
    }

    public function getTop10Users(){
        return $this->getEntityManager()
            ->createQuery(
                "SELECT u.id, u.username, MAX(s.createdAt) as createdAt  FROM AppBundle:Support s INNER JOIN UserBundle:User u WITH s.user = u.id GROUP BY u.id ORDER BY createdAt DESC"
            )
            ->setMaxResults(10)
            ->getResult();
    }

}
